# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "devise_traceable"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shenouda Bertel", "Patrick Veverka"]
  s.date = "2012-04-27"
  s.description = "Devise Traceable For Traceing Devise Models Logins and Logouts in separate model table"
  s.email = "patrick.veverka@stratumsecurity.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "devise_traceable.gemspec",
    "lib/devise_traceable.rb",
    "lib/devise_traceable/hooks/traceable.rb",
    "lib/devise_traceable/model.rb",
    "lib/devise_traceable/version.rb",
    "lib/devise_traceable/rails.rb",
    "lib/generators/devise_traceable/devise_traceable_generator.rb",
    "lib/generators/devise_traceable/templates/migration.rb"
  ]
  s.homepage = "http://github.com/threatsim/devise_traceable"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Devise Traceable For Traceing Devise Models"
  s.test_files = []

  if s.respond_to? :specification_version then
    s.specification_version = 3
  end
end